spring:
  flyway:
    baseline-on-migrate: true

  datasource:
    password: root
    url: jdbc:postgresql://localhost:5432/pastebin
    username: postgres
server:
  port: 8080
logging:
  level:
    org:
      springframework:
        security: debug